### ISSUE TITLE
I have an error

### ISSUE THREAD

**Issue by ghost** [tangkunyin/hexo-theme-jsimple#5]
```
Unhandled rejection TypeError: /home/u7/www/hexo.blog/themes/jsimple/layout/index.ejs:1
 >> 1| <%- partial('_partial/archive', {pagination: 2, index: true}) %>

/home/u7/www/hexo.blog/themes/jsimple/layout/_partial/archive.ejs:18
    16|     <!-- 首页默认取最最新文章集 -->
    17|     <% page.posts.sort('date', theme.homePageSortType).limit(theme.homeArticleShown).each(function(post){ %>
 >> 18|     <%- partial('_widget/category-items', {post: post}) %>
    19|     <% }) %>
    20|     <% } else { %>
    21|     <% page.posts.each(function(post){ %>

/home/u7/www/hexo.blog/themes/jsimple/layout/_widget/category-items.ejs:19
    17|         <a class="post-title" href="<%- url_for(post.path) %>" target="<%= external_link %>" title="<%= post.title %>"><%= post.title %></a>
    18|         <div class="post-meta">
 >> 19|             <a href="<%- url_for(post.path) %><%= config.duoshuo_shortname.length ? '#ds-thread' : '#disqus_thread' %>" target="<%= external_link %>">评论：?</a>
    20|             <em>·</em>
    21|             <a href="<%- url_for(post.path) %>" target="<%= external_link %>">阅读：?</a><em>·</em>
    22|             <span>喜欢：?</span>

Cannot read property 'length' of undefined
    at eval (eval at <anonymous> (/home/u7/www/hexo.blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1404)
    at eval (eval at <anonymous> (/home/u7/www/hexo.blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1895)
    at /home/u7/www/hexo.blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/u7/www/hexo.blog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/u7/www/hexo.blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/u7/www/hexo.blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/u7/www/hexo.blog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/u7/www/hexo.blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1011)
    at Query.forEach (/home/u7/www/hexo.blog/node_modules/warehouse/lib/query.js:42:5)
    at eval (eval at <anonymous> (/home/u7/www/hexo.blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:948)
    at eval (eval at <anonymous> (/home/u7/www/hexo.blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:33:66)
    at /home/u7/www/hexo.blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/u7/www/hexo.blog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/u7/www/hexo.blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/u7/www/hexo.blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/u7/www/hexo.blog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/u7/www/hexo.blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/home/u7/www/hexo.blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:103)
    at /home/u7/www/hexo.blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/u7/www/hexo.blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/u7/www/hexo.blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/u7/www/hexo.blog/node_modules/hexo/lib/hexo/index.js:387:25
```

**Comment by tangkunyin** [comment]
@dan1313 Make sure your `duoshuo_shortname` in your site _confiy.yml is config right.
May be this can be help:
https://github.com/tangkunyin/hexo-theme-jsimple/blob/master/README-en.md
