### ISSUE TITLE
主题hexo g报错

### ISSUE THREAD

**Issue by zengyong1990** [tangkunyin/hexo-theme-jsimple#9]
不能用 放弃

**Comment by tangkunyin** [comment]
@zengyong1990 遇到什么问题了？

**Comment by zengyong1990** [comment]
本地部署都失败  你自己下载试试

**Comment by jianpengzhang** [comment]
是的，我尝试了下，也是不能用，
hexo g 报错信息：
# hexo g
INFO  Start processing
INFO  Files loaded in 351 ms
Unhandled rejection TypeError: /home/work/jpzhang-blog-bak/themes/jsimple/layout/post.ejs:1
 >> 1| <%- partial('_partial/_post', {post: page, index: false}) %>

/home/work/jpzhang-blog-bak/themes/jsimple/layout/_partial/_post.ejs:5
    3|         <li><a href="/">最新</a></li>
    4|         <% for (var i in theme.menu){ %>
 >> 5|         <li class="<%= (page.categories.first().name == i) ? 'active' : '' %>">
    6|             <a href="/categories/<%= theme.menu[i] %>" data-name="<%= i %>"><%= i %></a>
    7|         </li>
    8|         <% } %>

Cannot read property 'name' of undefined
    at eval (eval at <anonymous> (/home/work/jpzhang-blog-bak/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:228)
    at eval (eval at <anonymous> (/home/work/jpzhang-blog-bak/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:670)
    at /home/work/jpzhang-blog-bak/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/work/jpzhang-blog-bak/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/work/jpzhang-blog-bak/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/work/jpzhang-blog-bak/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/work/jpzhang-blog-bak/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/work/jpzhang-blog-bak/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/home/work/jpzhang-blog-bak/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:99)
    at /home/work/jpzhang-blog-bak/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/work/jpzhang-blog-bak/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/work/jpzhang-blog-bak/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/work/jpzhang-blog-bak/node_modules/hexo/lib/hexo/index.js:388:25
    at tryCatcher (/home/work/jpzhang-blog-bak/node_modules/bluebird/js/release/util.js:16:23)
    at /home/work/jpzhang-blog-bak/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/work/jpzhang-blog-bak/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

不知道是不是文档没有写清楚还是配置有问题，

**Comment by damoncs** [comment]
@tangkunyin 他这个 问题还是   categories: ... 没有设置的原因。因为 默认的 helloworld那边文章 没有categories: ... 头信息。所以刚下载后的主题会报错。

@zengyong1990 @jianpengzhang 文章头添加上 categories: ... 就可以解决了

**Comment by tangkunyin** [comment]
@damoncs 说的对！
@jianpengzhang @zengyong1990 那个错其实不影响，鉴于强迫症，我已经改掉这个报错了，更新了文档，自己看吧：https://github.com/tangkunyin/hexo-theme-jsimple/blob/master/README.zhCN.md

**Comment by jianpengzhang** [comment]
ok, 谢谢啦

**Comment by tangkunyin** [comment]
@jianpengzhang 不客气
